[project]
name = "up-aag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "attrs>=25.1.0",
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
    "python-dateutil>=2.9.0.post0",
]
